// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseSkinsScope } from "./BaseSkinsScope";
import type { MapDecorationMode } from "./MapDecorationMode";
import type { MapSkinMode } from "./MapSkinMode";

/**
 * The built-in mods a user turned on, every one off by default.
 */
export type BuiltinModSettings = { 
/**
 * Every ward shows its own base skin.
 */
defaultWardSkins: boolean, 
/**
 * Which champions show their base skin on every skin.
 */
baseSkins: BaseSkinsScope, 
/**
 * Which map skin every game shows.
 */
mapSkin: MapSkinMode, 
/**
 * The `name` of the map skin [`MapSkinMode::Forced`] shows, kept while another mode is on.
 */
forcedMapSkin: string, 
/**
 * What each map decoration does, by the mutator that switches it. One absent follows the
 * game.
 */
mapDecorations: { [key in string]: MapDecorationMode }, };
