// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Doc } from "./Doc";
import type { PropertyDocs } from "./PropertyDocs";

/**
 * The wiki's documentation for one class and the properties declared on it and its bases.
 */
export type ClassDocs = { 
/**
 * The documentation of the class itself. Absent when the wiki documents only properties.
 */
class: Doc | null, 
/**
 * Keyed by the property's hash, `0x` and eight hex digits.
 */
properties: { [key in string]: PropertyDocs }, };
