// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The dependencies a body adds to and removes from a chunk's link list. ADR-0050.
 */
export type DeclaredLinks = { 
/**
 * The `links` items, in order.
 */
add: Array<string>, 
/**
 * The `-links` items, in order.
 */
remove: Array<string>, };
