// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredEntry } from "./DeclaredEntry";
import type { DeclaredLinks } from "./DeclaredLinks";
import type { LineSpan } from "./LineSpan";
import type { ModuleSelector } from "./ModuleSelector";

/**
 * One module of a manifest.
 */
export type DeclaredModule = { 
/**
 * The module's position in `modules`, zero-based.
 */
index: number, 
/**
 * The module's own name, where the manifest spells one.
 */
name: string | null, 
/**
 * The comment lines directly above the module, without their `#`.
 */
note: string | null, selector: ModuleSelector, 
/**
 * The chunk a `target` module edits, as spelled.
 */
target: string | null, 
/**
 * The path hash of the chunk a `target` module edits, 16 lowercase hex digits.
 */
targetHash: string | null, 
/**
 * The source file holding the module's edits. The spans of its entries and keys are
 * `None`, since they sit in that file.
 */
source: string | null, 
/**
 * The override files the module names, layer-relative.
 */
overrides: Array<string>, 
/**
 * The dependencies a `target` module adds to and removes from its chunk, over every edit.
 */
links: DeclaredLinks, 
/**
 * The module's first line.
 */
span: LineSpan | null, entries: Array<DeclaredEntry>, };
