// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an `objects` binding does to one object.
 */
export type DeclaredObjectEdit = { "kind": "clone", source: string, knownSource: string | null, } | { "kind": "construct", class: string, knownClass: string | null, } | { "kind": "remove" };
