// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredKey } from "./DeclaredKey";
import type { DeclaredLinks } from "./DeclaredLinks";
import type { DeclaredObjectEdit } from "./DeclaredObjectEdit";
import type { LineSpan } from "./LineSpan";

/**
 * One entry a module declares properties of, or one object it creates or removes.
 */
export type DeclaredEntry = { 
/**
 * The entry name as spelled.
 */
name: string, 
/**
 * The path the hashtables give a name spelled as a hash, `None` for any other name.
 */
knownName: string | null, 
/**
 * The object's path hash, `0x` and eight hex digits.
 */
hash: string, 
/**
 * The edit of a `target` module the entry sits in, zero-based.
 */
edit: number, 
/**
 * What an `objects` binding does to the object, `None` for an entry body.
 */
object: DeclaredObjectEdit | null, 
/**
 * The line naming the entry.
 */
span: LineSpan | null, keys: Array<DeclaredKey>, 
/**
 * The dependencies an `entries` module adds to and removes from each declaring chunk.
 */
links: DeclaredLinks, };
