// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The stages the define list is built from, in the order the engine runs them, later
 * winning.
 */
export type DefineSource = "material" | "feature" | "switch" | "pass" | "emitter";
