// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DefineSource } from "./DefineSource";

/**
 * One `NAME=VALUE` of the define list.
 */
export type Define = { name: string, value: string, 
/**
 * The last stage that set it.
 */
source: DefineSource, };
