// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The wiki's documentation for one class or one property. Each part is markdown.
 */
export type Doc = { 
/**
 * The main text. Absent when the entry has only notes or examples.
 */
description: string | null, 
/**
 * Short caveats, one paragraph each.
 */
notes: Array<string>, 
/**
 * Worked examples, one block each.
 */
examples: Array<string>, };
