// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A map skin every game can be made to show.
 */
export type ForcibleMapSkin = { 
/**
 * The skin's `name`, which the setting stores.
 */
name: string, 
/**
 * Each map archive holding a whole skin by that name, such as `Map11.wad.client`.
 */
maps: Array<string>, };
