// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeSighting } from "./CodeSighting";
import type { MessageSighting } from "./MessageSighting";

/**
 * What one game's log says, without the log.
 */
export type GameLogFacts = { 
/**
 * The wall clock the log opened at, from its first line.
 */
startedAt: string | null, buildVersion: string | null, contentVersion: string | null, gameBaseDir: string | null, 
/**
 * `-EnableCrashpad` against `-DisableCrashUploading`, which picks the DLL's scan.
 */
crashReporting: boolean | null, 
/**
 * Every code seen, in order, with its time.
 */
codes: Array<CodeSighting>, 
/**
 * Every uncoded record the reader knows, in order, with its time.
 */
messages: Array<MessageSighting>, 
/**
 * The last `LOAD` marker, which is the step that was running at the end.
 */
lastLoadStep: CodeSighting | null, loadingEnded: boolean, 
/**
 * A heuristic: `Loading Ended` was written, and at least one record came
 * later than it.
 */
reachedGameLoop: boolean, 
/**
 * `ALE-8SDFH23F` and the renderer's close, which a clean end writes.
 */
tornDown: boolean, errorLines: number, totalLines: number, lastTime: number, 
/**
 * The last forty lines, and ten around each coded line, with a record's
 * detail lines under it.
 */
excerpt: Array<string>, };
