// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ending } from "./Ending";
import type { Evidence } from "./Evidence";
import type { GameInfo } from "./GameInfo";
import type { GamePhase } from "./GamePhase";
import type { LaunchKind } from "./LaunchKind";
import type { OverlayOutcome } from "./OverlayOutcome";
import type { PatcherBinaries } from "./PatcherBinaries";
import type { ScanMode } from "./ScanMode";
import type { ScanStatus } from "./ScanStatus";
import type { SessionFailure } from "./SessionFailure";
import type { SessionOrigin } from "./SessionOrigin";
import type { ShaderFailure } from "./ShaderFailure";
import type { SkippedArchive } from "./SkippedArchive";
import type { Suspect } from "./Suspect";
import type { Verdict } from "./Verdict";

/**
 * The record the manager keeps for one game that went wrong.
 */
export type Incident = { 
/**
 * The game log's stamp, or the game's start when there is no log.
 */
id: string, 
/**
 * RFC 3339, UTC.
 */
startedAt: string, endedAt: string, 
/**
 * Library, or the workshop projects under test.
 */
origin: SessionOrigin, 
/**
 * Whether the DLL attached to this game.
 */
injected: boolean, hostElevated: boolean, patcher: PatcherBinaries, overlay: OverlayOutcome, overlayDetail: string | null, redirected: Array<string>, skipped: Array<SkippedArchive>, enabledCount: number, launch: LaunchKind, scan: ScanMode | null, scanStatus: ScanStatus | null, 
/**
 * The token the scan reported, beside [`Incident::scan_status`]'s reading
 * of it. The only part of a rejection a reader cannot get from the status.
 */
scanStatusCode: string | null, 
/**
 * How many archives the scan rejected. The verdict names the first, so
 * the rest is what a reader still has to be told about.
 */
scanRejected: number, 
/**
 * What the log says about the shaders, on a shader verdict.
 */
shader: ShaderFailure | null, phase: GamePhase, game: GameInfo | null, ending: Ending, 
/**
 * Set when the session failed before any game, which is the whole story.
 */
failure: SessionFailure | null, verdict: Verdict, evidence: Array<Evidence>, suspects: Array<Suspect>, 
/**
 * The user has seen it and closed the line.
 */
dismissed: boolean, };
