// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A record League writes with no code, which the reader knows by its words.
 */
export type LogMessage = "shader-compile-failed" | "missing-pipeline";
