// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A map decoration a mutator switches, which the map decorations mod can force off or on.
 */
export type MapDecoration = { 
/**
 * The mutator whose key switches the decoration, which the setting stores.
 */
mutator: string, 
/**
 * Each map archive with a container holding it, such as `Map11.wad.client`.
 */
maps: Array<string>, };
