// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a map decoration a mutator switches does, whatever mutators the game applies.
 */
export type MapDecorationMode = "hide" | "show";
