// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetRef } from "./AssetRef";
import type { MapPostEffects } from "./MapPostEffects";
import type { MapSsao } from "./MapSsao";
import type { MapSun } from "./MapSun";
import type { MaterialPreview } from "./MaterialPreview";

/**
 * One map's materials, one per path asked for and in that order, and its lighting and screen effects.
 */
export type MapModel = { 
/**
 * Null where the map's own bin declares no object at that path, which a backdrop
 * draws flat rather than not at all.
 */
materials: Array<MaterialPreview | null>, 
/**
 * Null where the map's container states no sun, which a backdrop lights with a default.
 */
sun: MapSun | null, 
/**
 * Null where the map's container states no post effects, which no shipped map does.
 */
postEffects: MapPostEffects | null, 
/**
 * Null where the map's container states no ambient occlusion, as all but one shipped map.
 */
ssao: MapSsao | null, 
/**
 * The `LightGrid.dat` the map lights its characters with, and null where it bakes
 * none or nothing holds it.
 */
lightGrid: AssetRef | null, };
