// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which map skin every game shows, whatever skin the server names.
 */
export type MapSkinMode = "game" | "classic" | "forced";
