// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogMessage } from "./LogMessage";

/**
 * One record League wrote with no code, with where and when.
 */
export type MessageSighting = { message: LogMessage, 
/**
 * Seconds into the log.
 */
at: number, 
/**
 * The whole record, redacted.
 */
line: string, 
/**
 * The lines under the record, in order and redacted like it.
 */
detail: Array<string>, };
