// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An engine particle shader pair, which the mesh an emitter resolves and its uv mode pick.
 *
 * The `particle_shaders` example finds each file in an installed shader cache.
 */
export type ParticleShader = "quad" | "quadFixedAlphaUv" | "quadScreenSpaceUv" | "quadSlice" | "mesh" | "meshSlice" | "attachedMesh" | "attachedMeshSlice" | "distortion" | "distortionMesh" | "distortionAttachedMesh";
