// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A define the engine sets on a particle shader from the emitter's fields, as `NAME=1`.
 *
 * `DISABLE_FOW` is the studio's, and `MASKED` and `COLORPALETTE_COLORBLIND` are never set
 * in a preview, so none of the three is here.
 */
export type ParticleDefine = "ALPHA_TEST" | "ALPHA_EROSION" | "MULT_PASS" | "SEPARATE_ALPHA_UV" | "SCREEN_SPACE_UV" | "LOCAL_SPACE_UV" | "PALETTIZE_TEXTURES" | "SOFT_PARTICLES" | "REFLECTIVE" | "USE_VERTEX_COLORS";
