// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Doc } from "./Doc";

/**
 * The wiki's documentation for one property, and the class whose page documents it.
 */
export type PropertyDocs = { 
/**
 * The declaring class as the wiki names it, or its hash where no name is known.
 */
owner: string, 
/**
 * The property as the wiki names it, or its hash where no name is known.
 */
name: string, doc: Doc, };
