// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an undo or a redo moved the rows of a tree, so a reader's expanded rows follow them.
 *
 * Paths are relative to the object `entry` names, `0x` and eight hex digits, as a row's are.
 */
export type Reshape = { "kind": "inPlace" } | { "kind": "inserted", entry: string, holder: string, index: number, } | { "kind": "removed", entry: string, path: string, } | { "kind": "moved", entry: string, path: string, to: number, } | { "kind": "rekeyed", entry: string, from: string, to: string, } | { "kind": "nulled", entry: string, path: string, };
