// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The files a path field wants ranked first in a search.
 *
 * Files with an expected extension rank first, then files from the field's archive,
 * then the bands decide. A preference changes the order of the matches and adds no match.
 */
export type SearchPreference = { 
/**
 * The extensions the field expects, without the dot. Empty means no preferred kind.
 */
extensions: Array<string>, 
/**
 * The file name of the field's archive, such as `Ahri.wad.client`.
 */
archive: string | null, };
