// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The shaders a game log reports as failed, as facts the frontend puts into words.
 */
export type ShaderFailure = { 
/**
 * Shader variants that did not compile, each counted once.
 */
variants: number, 
/**
 * Every failed variant named no vertex shader.
 */
unnamedPrograms: boolean, 
/**
 * The pipeline a material was drawn without, as League wrote it.
 */
missingPipeline: string | null, };
